### ISSUE TITLE
Argument counts are not validated

### ISSUE THREAD

**Issue by Fuyukai** [PurpleMyst/epython#4]
```py
def add(a, b):
    print(a + b)

add(1, 2, 3)
```

This prints 3, when it should error.

Additionally:

```py
def a(x, y):
        print(x * 1)

a(3)
```

This also prints 3.

**Comment by PurpleMyst** [comment]
Fixed in ddbbb1aabe888beb4d552709a2a5e992938dd828; Thank you for the report :smile:
